server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/pc_diy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pcdiy.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
